### ISSUE TITLE
Addon unavailable via Wago or WowUp

### ISSUE THREAD

**Issue by TheRealWebGremlin** [cliaz/Titan-Panel-Classic-Reagent-Tracker#13]
Hi, 

I wanted to inform you that the addon is not available on WowUp via GitHub, nor via Wago. On Wago, while the addon is listed on their site, there's no downloadable file provided. Similarly, WowUp can't utilize its GitHub integration because it needs the addon itself available as a zip rather than just the source code.

I hope you could take the time to look at this, thank you in advance.

Kind regards

**Comment by cliaz** [comment]
Hey mate, thanks for flagging that for me. I've just added a manually created zip to the v2.2.1 release - why WowUp won't classify the autogenerated tarball as a 'file' for its release workflow is beyond me - and I'm seeing it show up in the WowUp release list:

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/3636531/184528043-bee5c35d-ca8c-45c9-8efc-ecf5a073ef0e.png">


<img width="929" alt="image" src="https://user-images.githubusercontent.com/3636531/184528001-643bbcd2-9e99-40cb-abb1-565db115b9ad.png">


Let me know if that fixes things - I'm unable to test this stuff directly myself at the moment.

**Comment by TheRealWebGremlin** [comment]
Hey, thanks for looking at this. This has done the trick, it's now available for download on Wago, and by extension on WowUp too. Installing it via WowUp's Github integration does come up with a warning saying that it cannot verify which version of the game it is for, but it still installs just fine. I believe the zip would need to be suffixed with "-bc" for that warning to disappear. Either way, it works now! Thanks :)

**Comment by cliaz** [comment]
Hmm, I specifically configured the GitHub integration to use the .toc file for versioning. I’ll lea

**Comment by TheRealWebGremlin** [comment]
Same as before. It installs fine, just comes up with a warning that it can't verify for which client the addon is. There's no superfluous top-level folder.

From what I've read on WowUp's Discord, is that they need a "-bc" suffix in the zip's filename.  So I reckon renaming "TitanClassicReagentTracker.v2.2.1.zip" to "TitanClassicReagentTracker.v2.2.1-bc.zip" should do the trick.

**Comment by cliaz** [comment]
Ok good stuff. Was mainly wanting to ensure WowUp didn't install it to `Interface/Addons/TitanClassicReagentTracker/TitanClassicReagentTracker`
Glad to know it doesn't, thanks for checking that

I've renamed the zip file as you've suggested, will close this issue in a couple of days if that's all good.

**Comment by TheRealWebGremlin** [comment]
Checked once more, there are no warning message now. All issues resolved! Cheers!

**Comment by cliaz** [comment]
Excellent, thanks for being my tester 😂
