### ISSUE TITLE
Wotlk Classic

### ISSUE THREAD

**Issue by LordFnord23** [cliaz/Titan-Panel-Classic-Reagent-Tracker#14]
The reagents for Wotlk Classic are currently missing. An update would be greatly appreciated

**Comment by cliaz** [comment]
Hey mate, happy to do so - I just don't have an active wow sub at the moment so I can't get in and test functionality live.
If I push changes to a development branch, would you be able to test them for me? Once they work I'll release the stable version

**Comment by LordFnord23** [comment]
Thanks for the quick reply. I've overwritten the old files with the new ones, started the game and now the ReagentTracker doesn't even show up anymore. When checking the plugin menu of TitanPanel there is no option to activate ReagentTracker, so it's not just inactive.

**Comment by dyej** [comment]
Commenting to say I replaced the `spellData.lua` file (copied the raw source and edited file with it), and ReagentTracker is now working with Wild Spineleaf available to track on my druid.

**Comment by cliaz** [comment]
Hmm, two wildly opposing user testing reports hahaha. Thanks to you both for testing!
I just quickly checked the changed `spelldata.lua` file, and I don't seem to have LUA errors in there which would cause the addon to fail to load.

@LordFnord23 would you mind re-downloading the stock addon (via WowUp or your normal addon channel), and then replacing it with the file/content at https://raw.githubusercontent.com/cliaz/Titan-Panel-Classic-Reagent-Tracker/Wotlk-spells/spellData.lua

I'll push this live in a day or two if there's no further negative testing results.

**Comment by LordFnord23** [comment]
> @LordFnord23 would you mind re-downloading the stock addon (via WowUp or your normal addon channel), and then replacing it with the file/content at https://raw.githubusercontent.com/cliaz/Titan-Panel-Classic-Reagent-Tracker/Wotlk-spells/spellData.lua

I deleted everything and downloaded the new content again. This time it worked. Tracking as well as autobuying work perfectly. Thanks a lot
