### ISSUE TITLE
Reagent tracker not saving settings.

### ISSUE THREAD

**Issue by mtoedtem** [cliaz/Titan-Panel-Classic-Reagent-Tracker#18]
My tracker and autobuy options will sometimes clear out.

**Comment by cliaz** [comment]
Hi @mtoedtem, I'm using TitanPanel's variable store to save this addon's state between sessions - the file `TitanClassic.lua`.
All I can think of is that something's gone wrong with that file, so let's make a backup of the original, delete it, and create a new one to see if this fixes your issue.
**Note: This will remove your existing TitanPanel configuration! Make sure you backup the file (details below) before modifying things**


This TitanPanel variable store file is stored in the broader `SavedVariables` folder of your account in the WOW directory.
For example, with an account name of "**ApplesAreGreat**", the file would be in `World of Warcraft/_classic_/WTF/Account/ApplesAreGreat/SavedVariables/TitanClassic.lua`

Making sure the game is closed, make a copy of that file or simply rename it to `TitanClassic.lua.bak`, then open up wow and give it a crack again.
