### ISSUE TITLE
P3 WotLK - Addon won't work

### ISSUE THREAD

**Issue by Brown-Aaron** [cliaz/Titan-Panel-Classic-Reagent-Tracker#20]
As described in the title, since the launch of P3 the add-on no longer functions.

![image](https://github.com/cliaz/Titan-Panel-Classic-Reagent-Tracker/assets/20892387/9aec289b-b86f-445c-8910-485d09d6ae75)

**Comment by cliaz** [comment]
Hey, unfortunately I’m not going to be near my dev machine until the start of August. Will still be able to review and merge changes if someone has the chance to submit a fix, however I won’t be able to fix this in a timely manner.

**Comment by jones1973** [comment]
I compared how this plugin registered itself to how another Titan Panel one did. Not sure why the original version of this one doesn't work but it doesn't and this does *shrug*:

From original lines 106-108, change from:
```
addon.registry = {
    id = TITAN_REAGENTTRACKER_ID,
	version = GetAddOnMetadata("TitanReagentTracker", "Version"),   -- the the value of Version variable from the .toc
```
Change to:
```
local ADDON_NAME, L = ...;

addon.registry = {
    id = TITAN_REAGENTTRACKER_ID,
	version = GetAddOnMetadata(ADDON_NAME, "Version"), -- the the value of Version variable from the .toc
```

**Comment by Brown-Aaron** [comment]
I have verified that @jones1973's change works.

**Comment by cliaz** [comment]
Excellent, thanks to both of you - for the investigative work and suggested fix @jones1973, and for the testing effort @Brown-Aaron.

I’ve just landed in a country where I’ll have reliable internet again, so I’ll push this out in the next 6-12 hours.

**Comment by mc-dadmin** [comment]
The change is even more simple, The addon name on line 108 needs changed from "TitanReagentTracker" to "TitanClassicReagentTracker" and it works.

**Comment by cliaz** [comment]
> The change is even more simple, The addon name on line 108 needs changed from "TitanReagentTracker" to "TitanClassicReagentTracker" and it works.

That makes sense, but also shouldn't this have been causing issues for quite some time now, as the addon name doesn't match the parameters passed to the `GetAddOnMetadata` function

**Comment by cliaz** [comment]
Release pushed out as v3.0.3. I'll get back on in 8-10 hours and see how things are tracking
