### ISSUE TITLE
Allow specifying number of stacks

### ISSUE THREAD

**Issue by JesseNaranjo** [cliaz/Titan-Panel-Classic-Reagent-Tracker#3]
The addon currently purchases up to one full stack of the enabled reagent(s). This works well for most classes in most situations.

For raiding paladins - especially while progressing on content - one stack of Symbol of Kings may not always be enough. Here's some rough math:

- 100 symbols / 8 classes = 12.5 times buffing
- 12.5 buffs * 15 mins = 187.5 mins
- 187.5 mins / 60 mins = ~3 hours

The above math shows that 100 symbols to raid for three hours without wiping is enough. My personal preference would be to support allowing the user to specify the number of stacks to purchase.

To make things simple, the number of stacks could be predefined 1-10 in the context menu when right-clicking on the plugin.

Thoughts?

**Comment by cliaz** [comment]
Unfortunately enabling support for a custom number of reagents requires a full restructure of the code / addon logic. I'll take a look and see if there isn't some janky workaround I can implement.

**Comment by cliaz** [comment]
[This pull request](https://github.com/cliaz/Titan-Panel-Classic-Reagent-Tracker/pull/4) gives you the option to buy 3 stacks of Symbol of Kings. It's not great, but it will serve in the interim until I re-write the addon

**Comment by JesseNaranjo** [comment]
Hi cliaz - thanks for the change and the quick update! Will give it a whirl.

**Comment by jhenry82** [comment]
I would love to see this feature available for other classes besides Paladins, too. I'm often the only druid in a raid so need to carry around multiple stacks of Wild Thornroot. Have to manually restock if I want more than 20.

**Comment by panpaningame** [comment]
Neeeeeeeeeed !
I play Druid, Priest in Naxx, when we are on Horsemen, Sapphiron and KT, we need more than one stack.

Maybe we can change several lines of code to do it (dirty way :D) before the real update ?

**Comment by cliaz** [comment]
I feel your pain with the saph prog lol.
Ok, the (super janky) code is done - [Pull Request](https://github.com/cliaz/Titan-Panel-Classic-Reagent-Tracker/pull/5), [direct link to branch](https://github.com/cliaz/Titan-Panel-Classic-Reagent-Tracker/tree/feature/janky_multiple_stacks)

I can't test it right now cause my toons are wbuffed to the teeth (which is why I have time to code lol), anyone wanna volunteer to test? Not going to push to prod without testing.

**Comment by cliaz** [comment]
Addressed in tag 2.1.0
